INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 57, 'Ibadah Syukur Banua Niha Kristen Protestan (BNKP)', 'bnkp-ibadah-syukur', 'ibadah syukur bersama digelar oleh Banua Niha Kristen Protestan (BNKP). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>ibadah syukur bersama digelar oleh Banua Niha Kristen Protestan (BNKP). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Banua Niha Kristen Protestan (BNKP) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 57, 'Bakti Sosial Banua Niha Kristen Protestan (BNKP)', 'bnkp-bakti-sosial', 'bakti sosial digelar oleh Banua Niha Kristen Protestan (BNKP). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>bakti sosial digelar oleh Banua Niha Kristen Protestan (BNKP). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Banua Niha Kristen Protestan (BNKP) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 86, 'Rapat Koordinasi Gereja Allah Peduli Indonesia (GAPI)', 'gapi-rapat-koordinasi', 'rapat koordinasi rutin telah dilaksanakan oleh Gereja Allah Peduli Indonesia (GAPI). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>rapat koordinasi rutin telah dilaksanakan oleh Gereja Allah Peduli Indonesia (GAPI). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Allah Peduli Indonesia (GAPI) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 86, 'Seminar Keluarga Gereja Allah Peduli Indonesia (GAPI)', 'gapi-seminar-keluarga', 'seminar tentang keluarga Kristen diselenggarakan oleh Gereja Allah Peduli Indonesia (GAPI). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>seminar tentang keluarga Kristen diselenggarakan oleh Gereja Allah Peduli Indonesia (GAPI). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Allah Peduli Indonesia (GAPI) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 70, 'Pelayanan Kasih Gereja Anglikan (GA)', 'ga-pelayanan-kasih', 'pelayanan kasih telah dilaksanakan oleh Gereja Anglikan (GA). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>pelayanan kasih telah dilaksanakan oleh Gereja Anglikan (GA). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Anglikan (GA) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 70, 'Paskah Bersama Gereja Anglikan (GA)', 'ga-paskah-bersama', 'perayaan Paskah bersama digelar oleh Gereja Anglikan (GA). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>perayaan Paskah bersama digelar oleh Gereja Anglikan (GA). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Anglikan (GA) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 50, 'Retreat Pemuda Gereja Batak Karo Protestan (GBKP)', 'gbkp-retreat-pemuda', 'kegiatan retreat pemuda diikuti oleh Gereja Batak Karo Protestan (GBKP). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>kegiatan retreat pemuda diikuti oleh Gereja Batak Karo Protestan (GBKP). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Batak Karo Protestan (GBKP) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 50, 'Natal Bersama Gereja Batak Karo Protestan (GBKP)', 'gbkp-natal-bersama', 'perayaan Natal bersama diadakan oleh Gereja Batak Karo Protestan (GBKP). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>perayaan Natal bersama diadakan oleh Gereja Batak Karo Protestan (GBKP). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Batak Karo Protestan (GBKP) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 64, 'Bakti Sosial Gereja Bethel Indonesia (GBI)', 'gbi-bakti-sosial', 'bakti sosial digelar oleh Gereja Bethel Indonesia (GBI). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>bakti sosial digelar oleh Gereja Bethel Indonesia (GBI). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Bethel Indonesia (GBI) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 64, 'Ibadah Syukur Gereja Bethel Indonesia (GBI)', 'gbi-ibadah-syukur', 'ibadah syukur bersama digelar oleh Gereja Bethel Indonesia (GBI). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>ibadah syukur bersama digelar oleh Gereja Bethel Indonesia (GBI). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Bethel Indonesia (GBI) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 76, 'Seminar Keluarga Gereja Bethel Injil Sepenuh (GBIS)', 'gbis-seminar-keluarga', 'seminar tentang keluarga Kristen diselenggarakan oleh Gereja Bethel Injil Sepenuh (GBIS). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>seminar tentang keluarga Kristen diselenggarakan oleh Gereja Bethel Injil Sepenuh (GBIS). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Bethel Injil Sepenuh (GBIS) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 76, 'Rapat Koordinasi Gereja Bethel Injil Sepenuh (GBIS)', 'gbis-rapat-koordinasi', 'rapat koordinasi rutin telah dilaksanakan oleh Gereja Bethel Injil Sepenuh (GBIS). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>rapat koordinasi rutin telah dilaksanakan oleh Gereja Bethel Injil Sepenuh (GBIS). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Bethel Injil Sepenuh (GBIS) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 61, 'Paskah Bersama Gereja Gerakan Pentakosta (GGP)', 'ggp-paskah-bersama', 'perayaan Paskah bersama digelar oleh Gereja Gerakan Pentakosta (GGP). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>perayaan Paskah bersama digelar oleh Gereja Gerakan Pentakosta (GGP). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Gerakan Pentakosta (GGP) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 61, 'Pelayanan Kasih Gereja Gerakan Pentakosta (GGP)', 'ggp-pelayanan-kasih', 'pelayanan kasih telah dilaksanakan oleh Gereja Gerakan Pentakosta (GGP). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>pelayanan kasih telah dilaksanakan oleh Gereja Gerakan Pentakosta (GGP). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Gerakan Pentakosta (GGP) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 60, 'Natal Bersama Gereja Isa Almasih (GIA)', 'gia-natal-bersama', 'perayaan Natal bersama diadakan oleh Gereja Isa Almasih (GIA). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>perayaan Natal bersama diadakan oleh Gereja Isa Almasih (GIA). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Isa Almasih (GIA) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 60, 'Retreat Pemuda Gereja Isa Almasih (GIA)', 'gia-retreat-pemuda', 'kegiatan retreat pemuda diikuti oleh Gereja Isa Almasih (GIA). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>kegiatan retreat pemuda diikuti oleh Gereja Isa Almasih (GIA). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Isa Almasih (GIA) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 84, 'Ibadah Syukur Gereja Kasih Setia Indonesia (GKSI 64)', 'gksi-64-ibadah-syukur', 'ibadah syukur bersama digelar oleh Gereja Kasih Setia Indonesia (GKSI 64). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>ibadah syukur bersama digelar oleh Gereja Kasih Setia Indonesia (GKSI 64). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Kasih Setia Indonesia (GKSI 64) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 84, 'Bakti Sosial Gereja Kasih Setia Indonesia (GKSI 64)', 'gksi-64-bakti-sosial', 'bakti sosial digelar oleh Gereja Kasih Setia Indonesia (GKSI 64). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>bakti sosial digelar oleh Gereja Kasih Setia Indonesia (GKSI 64). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Kasih Setia Indonesia (GKSI 64) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 80, 'Rapat Koordinasi Gereja Kemah Injil Indonesia (GKII)', 'gkii-kemah-rapat-koordinasi', 'rapat koordinasi rutin telah dilaksanakan oleh Gereja Kemah Injil Indonesia (GKII). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>rapat koordinasi rutin telah dilaksanakan oleh Gereja Kemah Injil Indonesia (GKII). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Kemah Injil Indonesia (GKII) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 80, 'Seminar Keluarga Gereja Kemah Injil Indonesia (GKII)', 'gkii-kemah-seminar-keluarga', 'seminar tentang keluarga Kristen diselenggarakan oleh Gereja Kemah Injil Indonesia (GKII). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>seminar tentang keluarga Kristen diselenggarakan oleh Gereja Kemah Injil Indonesia (GKII). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Kemah Injil Indonesia (GKII) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 47, 'Pelayanan Kasih Gereja Kristen Indonesia (GKI)', 'gki-pelayanan-kasih', 'pelayanan kasih telah dilaksanakan oleh Gereja Kristen Indonesia (GKI). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>pelayanan kasih telah dilaksanakan oleh Gereja Kristen Indonesia (GKI). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Kristen Indonesia (GKI) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 47, 'Paskah Bersama Gereja Kristen Indonesia (GKI)', 'gki-paskah-bersama', 'perayaan Paskah bersama digelar oleh Gereja Kristen Indonesia (GKI). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>perayaan Paskah bersama digelar oleh Gereja Kristen Indonesia (GKI). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Kristen Indonesia (GKI) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 65, 'Retreat Pemuda Gereja Kristen Injili Indonesia (GKII)', 'gkii-retreat-pemuda', 'kegiatan retreat pemuda diikuti oleh Gereja Kristen Injili Indonesia (GKII). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>kegiatan retreat pemuda diikuti oleh Gereja Kristen Injili Indonesia (GKII). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Kristen Injili Indonesia (GKII) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 65, 'Natal Bersama Gereja Kristen Injili Indonesia (GKII)', 'gkii-natal-bersama', 'perayaan Natal bersama diadakan oleh Gereja Kristen Injili Indonesia (GKII). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>perayaan Natal bersama diadakan oleh Gereja Kristen Injili Indonesia (GKII). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Kristen Injili Indonesia (GKII) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 53, 'Bakti Sosial Gereja Kristen Jawa (GKJ)', 'gkj-bakti-sosial', 'bakti sosial digelar oleh Gereja Kristen Jawa (GKJ). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>bakti sosial digelar oleh Gereja Kristen Jawa (GKJ). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Kristen Jawa (GKJ) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 53, 'Ibadah Syukur Gereja Kristen Jawa (GKJ)', 'gkj-ibadah-syukur', 'ibadah syukur bersama digelar oleh Gereja Kristen Jawa (GKJ). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>ibadah syukur bersama digelar oleh Gereja Kristen Jawa (GKJ). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Kristen Jawa (GKJ) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 59, 'Seminar Keluarga Gereja Kristen Kalam Kudus (GKKK)', 'gkkk-seminar-keluarga', 'seminar tentang keluarga Kristen diselenggarakan oleh Gereja Kristen Kalam Kudus (GKKK). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>seminar tentang keluarga Kristen diselenggarakan oleh Gereja Kristen Kalam Kudus (GKKK). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Kristen Kalam Kudus (GKKK) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 59, 'Rapat Koordinasi Gereja Kristen Kalam Kudus (GKKK)', 'gkkk-rapat-koordinasi', 'rapat koordinasi rutin telah dilaksanakan oleh Gereja Kristen Kalam Kudus (GKKK). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>rapat koordinasi rutin telah dilaksanakan oleh Gereja Kristen Kalam Kudus (GKKK). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Kristen Kalam Kudus (GKKK) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 62, 'Paskah Bersama Gereja Kristen Muria Indonesia (GKMI)', 'gkmi-paskah-bersama', 'perayaan Paskah bersama digelar oleh Gereja Kristen Muria Indonesia (GKMI). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>perayaan Paskah bersama digelar oleh Gereja Kristen Muria Indonesia (GKMI). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Kristen Muria Indonesia (GKMI) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 62, 'Pelayanan Kasih Gereja Kristen Muria Indonesia (GKMI)', 'gkmi-pelayanan-kasih', 'pelayanan kasih telah dilaksanakan oleh Gereja Kristen Muria Indonesia (GKMI). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>pelayanan kasih telah dilaksanakan oleh Gereja Kristen Muria Indonesia (GKMI). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Kristen Muria Indonesia (GKMI) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 75, 'Natal Bersama Gereja Kristen Oikoumene Indonesia (GKOI)', 'gkoi-natal-bersama', 'perayaan Natal bersama diadakan oleh Gereja Kristen Oikoumene Indonesia (GKOI). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>perayaan Natal bersama diadakan oleh Gereja Kristen Oikoumene Indonesia (GKOI). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Kristen Oikoumene Indonesia (GKOI) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 75, 'Retreat Pemuda Gereja Kristen Oikoumene Indonesia (GKOI)', 'gkoi-retreat-pemuda', 'kegiatan retreat pemuda diikuti oleh Gereja Kristen Oikoumene Indonesia (GKOI). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>kegiatan retreat pemuda diikuti oleh Gereja Kristen Oikoumene Indonesia (GKOI). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Kristen Oikoumene Indonesia (GKOI) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 69, 'Ibadah Syukur Gereja Kristen Oikumene (GKO)', 'gko-ibadah-syukur', 'ibadah syukur bersama digelar oleh Gereja Kristen Oikumene (GKO). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>ibadah syukur bersama digelar oleh Gereja Kristen Oikumene (GKO). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Kristen Oikumene (GKO) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 69, 'Bakti Sosial Gereja Kristen Oikumene (GKO)', 'gko-bakti-sosial', 'bakti sosial digelar oleh Gereja Kristen Oikumene (GKO). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>bakti sosial digelar oleh Gereja Kristen Oikumene (GKO). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Kristen Oikumene (GKO) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 46, 'Rapat Koordinasi Gereja Kristen Pasundan (GKP)', 'gkp-rapat-koordinasi', 'rapat koordinasi rutin telah dilaksanakan oleh Gereja Kristen Pasundan (GKP). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>rapat koordinasi rutin telah dilaksanakan oleh Gereja Kristen Pasundan (GKP). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Kristen Pasundan (GKP) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 46, 'Seminar Keluarga Gereja Kristen Pasundan (GKP)', 'gkp-seminar-keluarga', 'seminar tentang keluarga Kristen diselenggarakan oleh Gereja Kristen Pasundan (GKP). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>seminar tentang keluarga Kristen diselenggarakan oleh Gereja Kristen Pasundan (GKP). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Kristen Pasundan (GKP) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 71, 'Pelayanan Kasih Gereja Kristen Pengabar Injil (GKPI) Citereup', 'gkpi-citereup-pelayanan-kasih', 'pelayanan kasih telah dilaksanakan oleh Gereja Kristen Pengabar Injil (GKPI) Citereup. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>pelayanan kasih telah dilaksanakan oleh Gereja Kristen Pengabar Injil (GKPI) Citereup. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Kristen Pengabar Injil (GKPI) Citereup dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 71, 'Paskah Bersama Gereja Kristen Pengabar Injil (GKPI) Citereup', 'gkpi-citereup-paskah-bersama', 'perayaan Paskah bersama digelar oleh Gereja Kristen Pengabar Injil (GKPI) Citereup. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>perayaan Paskah bersama digelar oleh Gereja Kristen Pengabar Injil (GKPI) Citereup. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Kristen Pengabar Injil (GKPI) Citereup semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 66, 'Retreat Pemuda Gereja Kristen Perjanjian Baru (GKPB)', 'gkpb-retreat-pemuda', 'kegiatan retreat pemuda diikuti oleh Gereja Kristen Perjanjian Baru (GKPB). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>kegiatan retreat pemuda diikuti oleh Gereja Kristen Perjanjian Baru (GKPB). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Kristen Perjanjian Baru (GKPB) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 66, 'Natal Bersama Gereja Kristen Perjanjian Baru (GKPB)', 'gkpb-natal-bersama', 'perayaan Natal bersama diadakan oleh Gereja Kristen Perjanjian Baru (GKPB). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>perayaan Natal bersama diadakan oleh Gereja Kristen Perjanjian Baru (GKPB). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Kristen Perjanjian Baru (GKPB) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 63, 'Bakti Sosial Gereja Kristen Protestan Angkola (GKPA)', 'gkpa-bakti-sosial', 'bakti sosial digelar oleh Gereja Kristen Protestan Angkola (GKPA). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>bakti sosial digelar oleh Gereja Kristen Protestan Angkola (GKPA). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Kristen Protestan Angkola (GKPA) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 63, 'Ibadah Syukur Gereja Kristen Protestan Angkola (GKPA)', 'gkpa-ibadah-syukur', 'ibadah syukur bersama digelar oleh Gereja Kristen Protestan Angkola (GKPA). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>ibadah syukur bersama digelar oleh Gereja Kristen Protestan Angkola (GKPA). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Kristen Protestan Angkola (GKPA) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 51, 'Seminar Keluarga Gereja Kristen Protestan Indonesia (GKPI)', 'gkpi-seminar-keluarga', 'seminar tentang keluarga Kristen diselenggarakan oleh Gereja Kristen Protestan Indonesia (GKPI). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>seminar tentang keluarga Kristen diselenggarakan oleh Gereja Kristen Protestan Indonesia (GKPI). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Kristen Protestan Indonesia (GKPI) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 51, 'Rapat Koordinasi Gereja Kristen Protestan Indonesia (GKPI)', 'gkpi-rapat-koordinasi', 'rapat koordinasi rutin telah dilaksanakan oleh Gereja Kristen Protestan Indonesia (GKPI). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>rapat koordinasi rutin telah dilaksanakan oleh Gereja Kristen Protestan Indonesia (GKPI). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Kristen Protestan Indonesia (GKPI) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 77, 'Paskah Bersama Gereja Kristen Protestan Jawa Barat (GKP Jabar)', 'gkp-jabar-paskah-bersama', 'perayaan Paskah bersama digelar oleh Gereja Kristen Protestan Jawa Barat (GKP Jabar). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>perayaan Paskah bersama digelar oleh Gereja Kristen Protestan Jawa Barat (GKP Jabar). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Kristen Protestan Jawa Barat (GKP Jabar) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 77, 'Pelayanan Kasih Gereja Kristen Protestan Jawa Barat (GKP Jabar)', 'gkp-jabar-pelayanan-kasih', 'pelayanan kasih telah dilaksanakan oleh Gereja Kristen Protestan Jawa Barat (GKP Jabar). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>pelayanan kasih telah dilaksanakan oleh Gereja Kristen Protestan Jawa Barat (GKP Jabar). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Kristen Protestan Jawa Barat (GKP Jabar) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 54, 'Natal Bersama Gereja Kristen Protestan Simalungun (GKPS)', 'gkps-natal-bersama', 'perayaan Natal bersama diadakan oleh Gereja Kristen Protestan Simalungun (GKPS). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>perayaan Natal bersama diadakan oleh Gereja Kristen Protestan Simalungun (GKPS). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Kristen Protestan Simalungun (GKPS) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 54, 'Retreat Pemuda Gereja Kristen Protestan Simalungun (GKPS)', 'gkps-retreat-pemuda', 'kegiatan retreat pemuda diikuti oleh Gereja Kristen Protestan Simalungun (GKPS). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>kegiatan retreat pemuda diikuti oleh Gereja Kristen Protestan Simalungun (GKPS). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Kristen Protestan Simalungun (GKPS) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 85, 'Ibadah Syukur Gereja Kristen Setia Indonesia (GKSI Sabas) 105', 'gksi-sabas-ibadah-syukur', 'ibadah syukur bersama digelar oleh Gereja Kristen Setia Indonesia (GKSI Sabas) 105. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>ibadah syukur bersama digelar oleh Gereja Kristen Setia Indonesia (GKSI Sabas) 105. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Kristen Setia Indonesia (GKSI Sabas) 105 dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 85, 'Bakti Sosial Gereja Kristen Setia Indonesia (GKSI Sabas) 105', 'gksi-sabas-bakti-sosial', 'bakti sosial digelar oleh Gereja Kristen Setia Indonesia (GKSI Sabas) 105. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>bakti sosial digelar oleh Gereja Kristen Setia Indonesia (GKSI Sabas) 105. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Kristen Setia Indonesia (GKSI Sabas) 105 semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 68, 'Rapat Koordinasi Gereja Kristus (GK)', 'gk-gereja-rapat-koordinasi', 'rapat koordinasi rutin telah dilaksanakan oleh Gereja Kristus (GK). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>rapat koordinasi rutin telah dilaksanakan oleh Gereja Kristus (GK). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Kristus (GK) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 68, 'Seminar Keluarga Gereja Kristus (GK)', 'gk-gereja-seminar-keluarga', 'seminar tentang keluarga Kristen diselenggarakan oleh Gereja Kristus (GK). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>seminar tentang keluarga Kristen diselenggarakan oleh Gereja Kristus (GK). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Kristus (GK) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 72, 'Pelayanan Kasih Gereja Kristus Rahmani Indonesia (GKRI)', 'gkri-pelayanan-kasih', 'pelayanan kasih telah dilaksanakan oleh Gereja Kristus Rahmani Indonesia (GKRI). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>pelayanan kasih telah dilaksanakan oleh Gereja Kristus Rahmani Indonesia (GKRI). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Kristus Rahmani Indonesia (GKRI) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 72, 'Paskah Bersama Gereja Kristus Rahmani Indonesia (GKRI)', 'gkri-paskah-bersama', 'perayaan Paskah bersama digelar oleh Gereja Kristus Rahmani Indonesia (GKRI). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>perayaan Paskah bersama digelar oleh Gereja Kristus Rahmani Indonesia (GKRI). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Kristus Rahmani Indonesia (GKRI) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 58, 'Retreat Pemuda Gereja Masehi Injili Sangihe Talaud (GMIST)', 'gmist-retreat-pemuda', 'kegiatan retreat pemuda diikuti oleh Gereja Masehi Injili Sangihe Talaud (GMIST). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>kegiatan retreat pemuda diikuti oleh Gereja Masehi Injili Sangihe Talaud (GMIST). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Masehi Injili Sangihe Talaud (GMIST) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 58, 'Natal Bersama Gereja Masehi Injili Sangihe Talaud (GMIST)', 'gmist-natal-bersama', 'perayaan Natal bersama diadakan oleh Gereja Masehi Injili Sangihe Talaud (GMIST). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>perayaan Natal bersama diadakan oleh Gereja Masehi Injili Sangihe Talaud (GMIST). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Masehi Injili Sangihe Talaud (GMIST) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 56, 'Bakti Sosial Gereja Methodist Indonesia (GMI)', 'gmi-bakti-sosial', 'bakti sosial digelar oleh Gereja Methodist Indonesia (GMI). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>bakti sosial digelar oleh Gereja Methodist Indonesia (GMI). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Methodist Indonesia (GMI) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 56, 'Ibadah Syukur Gereja Methodist Indonesia (GMI)', 'gmi-ibadah-syukur', 'ibadah syukur bersama digelar oleh Gereja Methodist Indonesia (GMI). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>ibadah syukur bersama digelar oleh Gereja Methodist Indonesia (GMI). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Methodist Indonesia (GMI) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 83, 'Seminar Keluarga Gereja Methodist Injili (GMI) INJILI', 'gmi-injili-seminar-keluarga', 'seminar tentang keluarga Kristen diselenggarakan oleh Gereja Methodist Injili (GMI) INJILI. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>seminar tentang keluarga Kristen diselenggarakan oleh Gereja Methodist Injili (GMI) INJILI. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Methodist Injili (GMI) INJILI dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 83, 'Rapat Koordinasi Gereja Methodist Injili (GMI) INJILI', 'gmi-injili-rapat-koordinasi', 'rapat koordinasi rutin telah dilaksanakan oleh Gereja Methodist Injili (GMI) INJILI. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>rapat koordinasi rutin telah dilaksanakan oleh Gereja Methodist Injili (GMI) INJILI. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Methodist Injili (GMI) INJILI semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 82, 'Paskah Bersama Gereja Misi Injili Indonesia (GMII)', 'gmii-paskah-bersama', 'perayaan Paskah bersama digelar oleh Gereja Misi Injili Indonesia (GMII). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>perayaan Paskah bersama digelar oleh Gereja Misi Injili Indonesia (GMII). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Misi Injili Indonesia (GMII) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 82, 'Pelayanan Kasih Gereja Misi Injili Indonesia (GMII)', 'gmii-pelayanan-kasih', 'pelayanan kasih telah dilaksanakan oleh Gereja Misi Injili Indonesia (GMII). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>pelayanan kasih telah dilaksanakan oleh Gereja Misi Injili Indonesia (GMII). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Misi Injili Indonesia (GMII) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 81, 'Natal Bersama Gereja Niha Keriso Protestan Indonesia (GNKPI)', 'gnkpi-natal-bersama', 'perayaan Natal bersama diadakan oleh Gereja Niha Keriso Protestan Indonesia (GNKPI). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>perayaan Natal bersama diadakan oleh Gereja Niha Keriso Protestan Indonesia (GNKPI). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Niha Keriso Protestan Indonesia (GNKPI) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 81, 'Retreat Pemuda Gereja Niha Keriso Protestan Indonesia (GNKPI)', 'gnkpi-retreat-pemuda', 'kegiatan retreat pemuda diikuti oleh Gereja Niha Keriso Protestan Indonesia (GNKPI). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>kegiatan retreat pemuda diikuti oleh Gereja Niha Keriso Protestan Indonesia (GNKPI). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Niha Keriso Protestan Indonesia (GNKPI) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 79, 'Ibadah Syukur Gereja Protestan Nusantara (GPN)', 'gpn-ibadah-syukur', 'ibadah syukur bersama digelar oleh Gereja Protestan Nusantara (GPN). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>ibadah syukur bersama digelar oleh Gereja Protestan Nusantara (GPN). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Protestan Nusantara (GPN) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 79, 'Bakti Sosial Gereja Protestan Nusantara (GPN)', 'gpn-bakti-sosial', 'bakti sosial digelar oleh Gereja Protestan Nusantara (GPN). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>bakti sosial digelar oleh Gereja Protestan Nusantara (GPN). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Protestan Nusantara (GPN) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 49, 'Rapat Koordinasi Gereja Protestan di Indonesia bagian Barat (GPIB)', 'gpib-rapat-koordinasi', 'rapat koordinasi rutin telah dilaksanakan oleh Gereja Protestan di Indonesia bagian Barat (GPIB). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>rapat koordinasi rutin telah dilaksanakan oleh Gereja Protestan di Indonesia bagian Barat (GPIB). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Protestan di Indonesia bagian Barat (GPIB) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 49, 'Seminar Keluarga Gereja Protestan di Indonesia bagian Barat (GPIB)', 'gpib-seminar-keluarga', 'seminar tentang keluarga Kristen diselenggarakan oleh Gereja Protestan di Indonesia bagian Barat (GPIB). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>seminar tentang keluarga Kristen diselenggarakan oleh Gereja Protestan di Indonesia bagian Barat (GPIB). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Protestan di Indonesia bagian Barat (GPIB) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 67, 'Pelayanan Kasih Gereja Rehoboth (GR)', 'gr-pelayanan-kasih', 'pelayanan kasih telah dilaksanakan oleh Gereja Rehoboth (GR). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>pelayanan kasih telah dilaksanakan oleh Gereja Rehoboth (GR). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Rehoboth (GR) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 67, 'Paskah Bersama Gereja Rehoboth (GR)', 'gr-paskah-bersama', 'perayaan Paskah bersama digelar oleh Gereja Rehoboth (GR). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>perayaan Paskah bersama digelar oleh Gereja Rehoboth (GR). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Rehoboth (GR) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 74, 'Retreat Pemuda Gereja Sidang Jemaat Allah (GSJA)', 'gsja-retreat-pemuda', 'kegiatan retreat pemuda diikuti oleh Gereja Sidang Jemaat Allah (GSJA). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>kegiatan retreat pemuda diikuti oleh Gereja Sidang Jemaat Allah (GSJA). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Sidang Jemaat Allah (GSJA) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 74, 'Natal Bersama Gereja Sidang Jemaat Allah (GSJA)', 'gsja-natal-bersama', 'perayaan Natal bersama diadakan oleh Gereja Sidang Jemaat Allah (GSJA). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>perayaan Natal bersama diadakan oleh Gereja Sidang Jemaat Allah (GSJA). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Sidang Jemaat Allah (GSJA) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 55, 'Bakti Sosial Gereja Toraja (GETOR)', 'getor-bakti-sosial', 'bakti sosial digelar oleh Gereja Toraja (GETOR). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>bakti sosial digelar oleh Gereja Toraja (GETOR). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Gereja Toraja (GETOR) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 55, 'Ibadah Syukur Gereja Toraja (GETOR)', 'getor-ibadah-syukur', 'ibadah syukur bersama digelar oleh Gereja Toraja (GETOR). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>ibadah syukur bersama digelar oleh Gereja Toraja (GETOR). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Gereja Toraja (GETOR) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 87, 'Seminar Keluarga HKPI (Calon Anggota)', 'hkpi-seminar-keluarga', 'seminar tentang keluarga Kristen diselenggarakan oleh HKPI (Calon Anggota). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>seminar tentang keluarga Kristen diselenggarakan oleh HKPI (Calon Anggota). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen HKPI (Calon Anggota) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 87, 'Rapat Koordinasi HKPI (Calon Anggota)', 'hkpi-rapat-koordinasi', 'rapat koordinasi rutin telah dilaksanakan oleh HKPI (Calon Anggota). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>rapat koordinasi rutin telah dilaksanakan oleh HKPI (Calon Anggota). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan HKPI (Calon Anggota) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 48, 'Paskah Bersama Huria Kristen Batak Protestan (HKBP)', 'hkbp-paskah-bersama', 'perayaan Paskah bersama digelar oleh Huria Kristen Batak Protestan (HKBP). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>perayaan Paskah bersama digelar oleh Huria Kristen Batak Protestan (HKBP). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Huria Kristen Batak Protestan (HKBP) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 48, 'Pelayanan Kasih Huria Kristen Batak Protestan (HKBP)', 'hkbp-pelayanan-kasih', 'pelayanan kasih telah dilaksanakan oleh Huria Kristen Batak Protestan (HKBP). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>pelayanan kasih telah dilaksanakan oleh Huria Kristen Batak Protestan (HKBP). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Huria Kristen Batak Protestan (HKBP) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 52, 'Natal Bersama Huria Kristen Indonesia (HKI)', 'hki-natal-bersama', 'perayaan Natal bersama diadakan oleh Huria Kristen Indonesia (HKI). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>perayaan Natal bersama diadakan oleh Huria Kristen Indonesia (HKI). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Huria Kristen Indonesia (HKI) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 52, 'Retreat Pemuda Huria Kristen Indonesia (HKI)', 'hki-retreat-pemuda', 'kegiatan retreat pemuda diikuti oleh Huria Kristen Indonesia (HKI). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>kegiatan retreat pemuda diikuti oleh Huria Kristen Indonesia (HKI). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Huria Kristen Indonesia (HKI) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 78, 'Ibadah Syukur Kerapatan Gereja Protestan Minahasa (KGPM)', 'kgpm-ibadah-syukur', 'ibadah syukur bersama digelar oleh Kerapatan Gereja Protestan Minahasa (KGPM). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>ibadah syukur bersama digelar oleh Kerapatan Gereja Protestan Minahasa (KGPM). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Kerapatan Gereja Protestan Minahasa (KGPM) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 78, 'Bakti Sosial Kerapatan Gereja Protestan Minahasa (KGPM)', 'kgpm-bakti-sosial', 'bakti sosial digelar oleh Kerapatan Gereja Protestan Minahasa (KGPM). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>bakti sosial digelar oleh Kerapatan Gereja Protestan Minahasa (KGPM). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Kerapatan Gereja Protestan Minahasa (KGPM) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 73, 'Rapat Koordinasi Orahua Niha Keriso Protestan (ONKP)', 'onkp-rapat-koordinasi', 'rapat koordinasi rutin telah dilaksanakan oleh Orahua Niha Keriso Protestan (ONKP). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>rapat koordinasi rutin telah dilaksanakan oleh Orahua Niha Keriso Protestan (ONKP). Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen Orahua Niha Keriso Protestan (ONKP) dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19'),
(2, 73, 'Seminar Keluarga Orahua Niha Keriso Protestan (ONKP)', 'onkp-seminar-keluarga', 'seminar tentang keluarga Kristen diselenggarakan oleh Orahua Niha Keriso Protestan (ONKP). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>seminar tentang keluarga Kristen diselenggarakan oleh Orahua Niha Keriso Protestan (ONKP). Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan Orahua Niha Keriso Protestan (ONKP) semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 21:08:19', '2026-06-02 21:08:19', '2026-06-02 21:08:19');

