INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 11, 'Ibadah Syukur PGIS Kota Bandung', 'pgis-kota-bandung-ibadah-syukur', 'ibadah syukur bersama digelar oleh PGIS Kota Bandung. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>ibadah syukur bersama digelar oleh PGIS Kota Bandung. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen PGIS Kota Bandung dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:38:27', '2026-06-02 20:38:27', '2026-06-02 20:38:27'),
(2, 11, 'Retreat Pemuda PGIS Kota Bandung', 'pgis-kota-bandung-retreat-pemuda', 'kegiatan retreat pemuda diikuti oleh pemuda dari PGIS Kota Bandung. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>kegiatan retreat pemuda diikuti oleh pemuda dari PGIS Kota Bandung. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan PGIS Kota Bandung semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:38:27', '2026-06-02 20:38:27', '2026-06-02 20:38:27');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 12, 'Rapat Koordinasi PGIS Kota Cimahi', 'pgis-kota-cimahi-rapat-koordinasi', 'rapat koordinasi rutin telah dilaksanakan oleh PGIS Kota Cimahi. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>rapat koordinasi rutin telah dilaksanakan oleh PGIS Kota Cimahi. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen PGIS Kota Cimahi dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:38:27', '2026-06-02 20:38:27', '2026-06-02 20:38:27'),
(2, 12, 'Bakti Sosial PGIS Kota Cimahi', 'pgis-kota-cimahi-bakti-sosial', 'bakti sosial digelar oleh PGIS Kota Cimahi. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>bakti sosial digelar oleh PGIS Kota Cimahi. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan PGIS Kota Cimahi semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:38:27', '2026-06-02 20:38:27', '2026-06-02 20:38:27');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 13, 'Pelayanan Kasih PGIS Kabupaten Bandung', 'pgis-kab-bandung-pelayanan-kasih', 'pelayanan kasih telah dilaksanakan oleh PGIS Kabupaten Bandung. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>pelayanan kasih telah dilaksanakan oleh PGIS Kabupaten Bandung. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen PGIS Kabupaten Bandung dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:38:27', '2026-06-02 20:38:27', '2026-06-02 20:38:27'),
(2, 13, 'Ibadah Syukur PGIS Kabupaten Bandung', 'pgis-kab-bandung-ibadah-syukur', 'ibadah syukur bersama digelar oleh PGIS Kabupaten Bandung. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>ibadah syukur bersama digelar oleh PGIS Kabupaten Bandung. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan PGIS Kabupaten Bandung semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:38:27', '2026-06-02 20:38:27', '2026-06-02 20:38:27');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 14, 'Retreat Pemuda PGIS Kabupaten Bandung Barat', 'pgis-kab-bandung-barat-retreat-pemuda', 'kegiatan retreat pemuda diikuti oleh pemuda dari PGIS Kabupaten Bandung Barat. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>kegiatan retreat pemuda diikuti oleh pemuda dari PGIS Kabupaten Bandung Barat. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen PGIS Kabupaten Bandung Barat dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:38:27', '2026-06-02 20:38:27', '2026-06-02 20:38:27'),
(2, 14, 'Rapat Koordinasi PGIS Kabupaten Bandung Barat', 'pgis-kab-bandung-barat-rapat-koordinasi', 'rapat koordinasi rutin telah dilaksanakan oleh PGIS Kabupaten Bandung Barat. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>rapat koordinasi rutin telah dilaksanakan oleh PGIS Kabupaten Bandung Barat. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan PGIS Kabupaten Bandung Barat semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:38:27', '2026-06-02 20:38:27', '2026-06-02 20:38:27');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 15, 'Bakti Sosial PGIS Kabupaten Karawang', 'pgis-kab-karawang-bakti-sosial', 'bakti sosial digelar oleh PGIS Kabupaten Karawang. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>bakti sosial digelar oleh PGIS Kabupaten Karawang. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen PGIS Kabupaten Karawang dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:38:27', '2026-06-02 20:38:27', '2026-06-02 20:38:27'),
(2, 15, 'Pelayanan Kasih PGIS Kabupaten Karawang', 'pgis-kab-karawang-pelayanan-kasih', 'pelayanan kasih telah dilaksanakan oleh PGIS Kabupaten Karawang. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>pelayanan kasih telah dilaksanakan oleh PGIS Kabupaten Karawang. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan PGIS Kabupaten Karawang semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:38:27', '2026-06-02 20:38:27', '2026-06-02 20:38:27');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 16, 'Ibadah Syukur PGIS Kota Bekasi', 'pgis-kota-bekasi-ibadah-syukur', 'ibadah syukur bersama digelar oleh PGIS Kota Bekasi. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>ibadah syukur bersama digelar oleh PGIS Kota Bekasi. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen PGIS Kota Bekasi dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:38:27', '2026-06-02 20:38:27', '2026-06-02 20:38:27'),
(2, 16, 'Retreat Pemuda PGIS Kota Bekasi', 'pgis-kota-bekasi-retreat-pemuda', 'kegiatan retreat pemuda diikuti oleh pemuda dari PGIS Kota Bekasi. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>kegiatan retreat pemuda diikuti oleh pemuda dari PGIS Kota Bekasi. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan PGIS Kota Bekasi semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:38:27', '2026-06-02 20:38:27', '2026-06-02 20:38:27');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 17, 'Rapat Koordinasi PGIS Kabupaten Bekasi', 'pgis-kab-bekasi-rapat-koordinasi', 'rapat koordinasi rutin telah dilaksanakan oleh PGIS Kabupaten Bekasi. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>rapat koordinasi rutin telah dilaksanakan oleh PGIS Kabupaten Bekasi. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen PGIS Kabupaten Bekasi dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:38:27', '2026-06-02 20:38:27', '2026-06-02 20:38:27'),
(2, 17, 'Bakti Sosial PGIS Kabupaten Bekasi', 'pgis-kab-bekasi-bakti-sosial', 'bakti sosial digelar oleh PGIS Kabupaten Bekasi. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>bakti sosial digelar oleh PGIS Kabupaten Bekasi. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan PGIS Kabupaten Bekasi semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:38:27', '2026-06-02 20:38:27', '2026-06-02 20:38:27');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 18, 'Pelayanan Kasih PGIS Kota Depok', 'pgis-kota-depok-pelayanan-kasih', 'pelayanan kasih telah dilaksanakan oleh PGIS Kota Depok. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>pelayanan kasih telah dilaksanakan oleh PGIS Kota Depok. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen PGIS Kota Depok dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:38:27', '2026-06-02 20:38:27', '2026-06-02 20:38:27'),
(2, 18, 'Ibadah Syukur PGIS Kota Depok', 'pgis-kota-depok-ibadah-syukur', 'ibadah syukur bersama digelar oleh PGIS Kota Depok. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>ibadah syukur bersama digelar oleh PGIS Kota Depok. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan PGIS Kota Depok semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:38:27', '2026-06-02 20:38:27', '2026-06-02 20:38:27');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 19, 'Retreat Pemuda PGIS Kota Bogor', 'pgis-kota-bogor-retreat-pemuda', 'kegiatan retreat pemuda diikuti oleh pemuda dari PGIS Kota Bogor. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>kegiatan retreat pemuda diikuti oleh pemuda dari PGIS Kota Bogor. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen PGIS Kota Bogor dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:38:27', '2026-06-02 20:38:27', '2026-06-02 20:38:27'),
(2, 19, 'Rapat Koordinasi PGIS Kota Bogor', 'pgis-kota-bogor-rapat-koordinasi', 'rapat koordinasi rutin telah dilaksanakan oleh PGIS Kota Bogor. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>rapat koordinasi rutin telah dilaksanakan oleh PGIS Kota Bogor. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan PGIS Kota Bogor semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:38:27', '2026-06-02 20:38:27', '2026-06-02 20:38:27');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 20, 'Bakti Sosial PGIS Kabupaten Bogor', 'pgis-kab-bogor-bakti-sosial', 'bakti sosial digelar oleh PGIS Kabupaten Bogor. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>bakti sosial digelar oleh PGIS Kabupaten Bogor. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen PGIS Kabupaten Bogor dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:38:27', '2026-06-02 20:38:27', '2026-06-02 20:38:27'),
(2, 20, 'Pelayanan Kasih PGIS Kabupaten Bogor', 'pgis-kab-bogor-pelayanan-kasih', 'pelayanan kasih telah dilaksanakan oleh PGIS Kabupaten Bogor. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>pelayanan kasih telah dilaksanakan oleh PGIS Kabupaten Bogor. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan PGIS Kabupaten Bogor semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:38:27', '2026-06-02 20:38:27', '2026-06-02 20:38:27');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 21, 'Ibadah Syukur PGIS Sukabumi', 'pgis-sukabumi-ibadah-syukur', 'ibadah syukur bersama digelar oleh PGIS Sukabumi. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>ibadah syukur bersama digelar oleh PGIS Sukabumi. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen PGIS Sukabumi dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:38:27', '2026-06-02 20:38:27', '2026-06-02 20:38:27'),
(2, 21, 'Retreat Pemuda PGIS Sukabumi', 'pgis-sukabumi-retreat-pemuda', 'kegiatan retreat pemuda diikuti oleh pemuda dari PGIS Sukabumi. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>kegiatan retreat pemuda diikuti oleh pemuda dari PGIS Sukabumi. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan PGIS Sukabumi semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:38:27', '2026-06-02 20:38:27', '2026-06-02 20:38:27');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 22, 'Rapat Koordinasi PGIS Cirebon', 'pgis-cirebon-rapat-koordinasi', 'rapat koordinasi rutin telah dilaksanakan oleh PGIS Cirebon. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>rapat koordinasi rutin telah dilaksanakan oleh PGIS Cirebon. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen PGIS Cirebon dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:38:27', '2026-06-02 20:38:27', '2026-06-02 20:38:27'),
(2, 22, 'Bakti Sosial PGIS Cirebon', 'pgis-cirebon-bakti-sosial', 'bakti sosial digelar oleh PGIS Cirebon. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>bakti sosial digelar oleh PGIS Cirebon. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan PGIS Cirebon semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:38:27', '2026-06-02 20:38:27', '2026-06-02 20:38:27');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 23, 'Pelayanan Kasih PGIS Cianjur', 'pgis-cianjur-pelayanan-kasih', 'pelayanan kasih telah dilaksanakan oleh PGIS Cianjur. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>pelayanan kasih telah dilaksanakan oleh PGIS Cianjur. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen PGIS Cianjur dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:38:27', '2026-06-02 20:38:27', '2026-06-02 20:38:27'),
(2, 23, 'Ibadah Syukur PGIS Cianjur', 'pgis-cianjur-ibadah-syukur', 'ibadah syukur bersama digelar oleh PGIS Cianjur. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>ibadah syukur bersama digelar oleh PGIS Cianjur. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan PGIS Cianjur semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:38:27', '2026-06-02 20:38:27', '2026-06-02 20:38:27');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 24, 'Retreat Pemuda PGIS Subang', 'pgis-subang-retreat-pemuda', 'kegiatan retreat pemuda diikuti oleh pemuda dari PGIS Subang. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>kegiatan retreat pemuda diikuti oleh pemuda dari PGIS Subang. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen PGIS Subang dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:38:27', '2026-06-02 20:38:27', '2026-06-02 20:38:27'),
(2, 24, 'Rapat Koordinasi PGIS Subang', 'pgis-subang-rapat-koordinasi', 'rapat koordinasi rutin telah dilaksanakan oleh PGIS Subang. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>rapat koordinasi rutin telah dilaksanakan oleh PGIS Subang. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan PGIS Subang semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:38:27', '2026-06-02 20:38:27', '2026-06-02 20:38:27');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 25, 'Bakti Sosial PGIS Purwakarta', 'pgis-purwakarta-bakti-sosial', 'bakti sosial digelar oleh PGIS Purwakarta. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>bakti sosial digelar oleh PGIS Purwakarta. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen PGIS Purwakarta dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:38:27', '2026-06-02 20:38:27', '2026-06-02 20:38:27'),
(2, 25, 'Pelayanan Kasih PGIS Purwakarta', 'pgis-purwakarta-pelayanan-kasih', 'pelayanan kasih telah dilaksanakan oleh PGIS Purwakarta. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>pelayanan kasih telah dilaksanakan oleh PGIS Purwakarta. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan PGIS Purwakarta semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:38:27', '2026-06-02 20:38:27', '2026-06-02 20:38:27');

