INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 26, 'Ibadah Minggu POUK Depok II Timur', 'pouk-depok-ii-timur-ibadah-minggu', 'ibadah minggu bersama digelar oleh POUK Depok II Timur. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>ibadah minggu bersama digelar oleh POUK Depok II Timur. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen POUK Depok II Timur dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03'),
(2, 26, 'Pelayanan Anak POUK Depok II Timur', 'pouk-depok-ii-timur-pelayanan-anak', 'kegiatan pelayanan anak diselenggarakan oleh POUK Depok II Timur. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>kegiatan pelayanan anak diselenggarakan oleh POUK Depok II Timur. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan POUK Depok II Timur semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 27, 'Persekutuan Doa POUK Pelita', 'pouk-pelita-persekutuan-doa', 'persekutuan doa rutin dilaksanakan oleh POUK Pelita. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>persekutuan doa rutin dilaksanakan oleh POUK Pelita. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen POUK Pelita dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03'),
(2, 27, 'Katekisasi POUK Pelita', 'pouk-pelita-katekisasi', 'katekisasi jemaat baru dilaksanakan oleh POUK Pelita. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>katekisasi jemaat baru dilaksanakan oleh POUK Pelita. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan POUK Pelita semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 28, 'Pelayanan Anak POUK Dian Kasih', 'pouk-dian-kasih-pelayanan-anak', 'kegiatan pelayanan anak diselenggarakan oleh POUK Dian Kasih. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>kegiatan pelayanan anak diselenggarakan oleh POUK Dian Kasih. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen POUK Dian Kasih dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03'),
(2, 28, 'Perjamuan Kasih POUK Dian Kasih', 'pouk-dian-kasih-perjamuan-kasih', 'perjamuan kasih digelar oleh POUK Dian Kasih. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>perjamuan kasih digelar oleh POUK Dian Kasih. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan POUK Dian Kasih semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 29, 'Katekisasi POUK Pelni', 'pouk-pelni-katekisasi', 'katekisasi jemaat baru dilaksanakan oleh POUK Pelni. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>katekisasi jemaat baru dilaksanakan oleh POUK Pelni. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen POUK Pelni dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03'),
(2, 29, 'Ibadah Minggu POUK Pelni', 'pouk-pelni-ibadah-minggu', 'ibadah minggu bersama digelar oleh POUK Pelni. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>ibadah minggu bersama digelar oleh POUK Pelni. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan POUK Pelni semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 30, 'Perjamuan Kasih POUK Bumi Dirgantara Permai', 'pouk-bumi-dirgantara-permai-perjamuan-kasih', 'perjamuan kasih digelar oleh POUK Bumi Dirgantara Permai. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>perjamuan kasih digelar oleh POUK Bumi Dirgantara Permai. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen POUK Bumi Dirgantara Permai dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03'),
(2, 30, 'Persekutuan Doa POUK Bumi Dirgantara Permai', 'pouk-bumi-dirgantara-permai-persekutuan-doa', 'persekutuan doa rutin dilaksanakan oleh POUK Bumi Dirgantara Permai. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>persekutuan doa rutin dilaksanakan oleh POUK Bumi Dirgantara Permai. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan POUK Bumi Dirgantara Permai semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 31, 'Ibadah Minggu POU PUKris Kota Wisata', 'pou-pukris-kota-wisata-ibadah-minggu', 'ibadah minggu bersama digelar oleh POU PUKris Kota Wisata. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>ibadah minggu bersama digelar oleh POU PUKris Kota Wisata. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen POU PUKris Kota Wisata dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03'),
(2, 31, 'Pelayanan Anak POU PUKris Kota Wisata', 'pou-pukris-kota-wisata-pelayanan-anak', 'kegiatan pelayanan anak diselenggarakan oleh POU PUKris Kota Wisata. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>kegiatan pelayanan anak diselenggarakan oleh POU PUKris Kota Wisata. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan POU PUKris Kota Wisata semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 32, 'Persekutuan Doa POUK Citra Gran', 'pouk-citra-gran-persekutuan-doa', 'persekutuan doa rutin dilaksanakan oleh POUK Citra Gran. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>persekutuan doa rutin dilaksanakan oleh POUK Citra Gran. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen POUK Citra Gran dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03'),
(2, 32, 'Katekisasi POUK Citra Gran', 'pouk-citra-gran-katekisasi', 'katekisasi jemaat baru dilaksanakan oleh POUK Citra Gran. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>katekisasi jemaat baru dilaksanakan oleh POUK Citra Gran. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan POUK Citra Gran semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 33, 'Pelayanan Anak POUK TNI AL Ciangsana', 'pouk-tni-al-ciangsana-pelayanan-anak', 'kegiatan pelayanan anak diselenggarakan oleh POUK TNI AL Ciangsana. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>kegiatan pelayanan anak diselenggarakan oleh POUK TNI AL Ciangsana. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen POUK TNI AL Ciangsana dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03'),
(2, 33, 'Perjamuan Kasih POUK TNI AL Ciangsana', 'pouk-tni-al-ciangsana-perjamuan-kasih', 'perjamuan kasih digelar oleh POUK TNI AL Ciangsana. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>perjamuan kasih digelar oleh POUK TNI AL Ciangsana. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan POUK TNI AL Ciangsana semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 34, 'Katekisasi POUK Yon Pomad', 'pouk-yon-pomad-katekisasi', 'katekisasi jemaat baru dilaksanakan oleh POUK Yon Pomad. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>katekisasi jemaat baru dilaksanakan oleh POUK Yon Pomad. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen POUK Yon Pomad dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03'),
(2, 34, 'Ibadah Minggu POUK Yon Pomad', 'pouk-yon-pomad-ibadah-minggu', 'ibadah minggu bersama digelar oleh POUK Yon Pomad. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>ibadah minggu bersama digelar oleh POUK Yon Pomad. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan POUK Yon Pomad semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 35, 'Perjamuan Kasih POUK Graha Prima', 'pouk-graha-prima-perjamuan-kasih', 'perjamuan kasih digelar oleh POUK Graha Prima. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>perjamuan kasih digelar oleh POUK Graha Prima. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen POUK Graha Prima dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03'),
(2, 35, 'Persekutuan Doa POUK Graha Prima', 'pouk-graha-prima-persekutuan-doa', 'persekutuan doa rutin dilaksanakan oleh POUK Graha Prima. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>persekutuan doa rutin dilaksanakan oleh POUK Graha Prima. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan POUK Graha Prima semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 36, 'Ibadah Minggu POUK Kemang Pratama', 'pouk-kemang-pratama-ibadah-minggu', 'ibadah minggu bersama digelar oleh POUK Kemang Pratama. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>ibadah minggu bersama digelar oleh POUK Kemang Pratama. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen POUK Kemang Pratama dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03'),
(2, 36, 'Pelayanan Anak POUK Kemang Pratama', 'pouk-kemang-pratama-pelayanan-anak', 'kegiatan pelayanan anak diselenggarakan oleh POUK Kemang Pratama. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>kegiatan pelayanan anak diselenggarakan oleh POUK Kemang Pratama. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan POUK Kemang Pratama semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 37, 'Persekutuan Doa POUK Anugerah Taman Galaxi Indah', 'pouk-taman-galaxi-indah-persekutuan-doa', 'persekutuan doa rutin dilaksanakan oleh POUK Anugerah Taman Galaxi Indah. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>persekutuan doa rutin dilaksanakan oleh POUK Anugerah Taman Galaxi Indah. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen POUK Anugerah Taman Galaxi Indah dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03'),
(2, 37, 'Katekisasi POUK Anugerah Taman Galaxi Indah', 'pouk-taman-galaxi-indah-katekisasi', 'katekisasi jemaat baru dilaksanakan oleh POUK Anugerah Taman Galaxi Indah. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>katekisasi jemaat baru dilaksanakan oleh POUK Anugerah Taman Galaxi Indah. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan POUK Anugerah Taman Galaxi Indah semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 38, 'Pelayanan Anak POUK Lanud Atangsanjaya', 'pouk-lanud-atangsanjaya-pelayanan-anak', 'kegiatan pelayanan anak diselenggarakan oleh POUK Lanud Atangsanjaya. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>kegiatan pelayanan anak diselenggarakan oleh POUK Lanud Atangsanjaya. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen POUK Lanud Atangsanjaya dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03'),
(2, 38, 'Perjamuan Kasih POUK Lanud Atangsanjaya', 'pouk-lanud-atangsanjaya-perjamuan-kasih', 'perjamuan kasih digelar oleh POUK Lanud Atangsanjaya. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>perjamuan kasih digelar oleh POUK Lanud Atangsanjaya. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan POUK Lanud Atangsanjaya semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 39, 'Katekisasi POUK Suryadharma', 'pouk-suryadharma-katekisasi', 'katekisasi jemaat baru dilaksanakan oleh POUK Suryadharma. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>katekisasi jemaat baru dilaksanakan oleh POUK Suryadharma. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen POUK Suryadharma dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03'),
(2, 39, 'Ibadah Minggu POUK Suryadharma', 'pouk-suryadharma-ibadah-minggu', 'ibadah minggu bersama digelar oleh POUK Suryadharma. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>ibadah minggu bersama digelar oleh POUK Suryadharma. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan POUK Suryadharma semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 40, 'Perjamuan Kasih POUK GPI IPDN', 'pouk-gpi-ipdn-perjamuan-kasih', 'perjamuan kasih digelar oleh POUK GPI IPDN. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>perjamuan kasih digelar oleh POUK GPI IPDN. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen POUK GPI IPDN dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03'),
(2, 40, 'Persekutuan Doa POUK GPI IPDN', 'pouk-gpi-ipdn-persekutuan-doa', 'persekutuan doa rutin dilaksanakan oleh POUK GPI IPDN. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>persekutuan doa rutin dilaksanakan oleh POUK GPI IPDN. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan POUK GPI IPDN semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 41, 'Ibadah Minggu POUK GKPO Lanud Sulaiman', 'pouk-lanud-sulaiman-ibadah-minggu', 'ibadah minggu bersama digelar oleh POUK GKPO Lanud Sulaiman. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>ibadah minggu bersama digelar oleh POUK GKPO Lanud Sulaiman. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen POUK GKPO Lanud Sulaiman dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03'),
(2, 41, 'Pelayanan Anak POUK GKPO Lanud Sulaiman', 'pouk-lanud-sulaiman-pelayanan-anak', 'kegiatan pelayanan anak diselenggarakan oleh POUK GKPO Lanud Sulaiman. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>kegiatan pelayanan anak diselenggarakan oleh POUK GKPO Lanud Sulaiman. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan POUK GKPO Lanud Sulaiman semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 42, 'Persekutuan Doa POUK Husein Sastranegara', 'pouk-husein-sastranegara-persekutuan-doa', 'persekutuan doa rutin dilaksanakan oleh POUK Husein Sastranegara. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>persekutuan doa rutin dilaksanakan oleh POUK Husein Sastranegara. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen POUK Husein Sastranegara dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03'),
(2, 42, 'Katekisasi POUK Husein Sastranegara', 'pouk-husein-sastranegara-katekisasi', 'katekisasi jemaat baru dilaksanakan oleh POUK Husein Sastranegara. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>katekisasi jemaat baru dilaksanakan oleh POUK Husein Sastranegara. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan POUK Husein Sastranegara semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 43, 'Pelayanan Anak POUK Legenda Wisata', 'pouk-legenda-wisata-pelayanan-anak', 'kegiatan pelayanan anak diselenggarakan oleh POUK Legenda Wisata. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>kegiatan pelayanan anak diselenggarakan oleh POUK Legenda Wisata. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen POUK Legenda Wisata dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03'),
(2, 43, 'Perjamuan Kasih POUK Legenda Wisata', 'pouk-legenda-wisata-perjamuan-kasih', 'perjamuan kasih digelar oleh POUK Legenda Wisata. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>perjamuan kasih digelar oleh POUK Legenda Wisata. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan POUK Legenda Wisata semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 44, 'Katekisasi POUK Ekklesia Batujajar', 'pouk-ekklesia-batujajar-katekisasi', 'katekisasi jemaat baru dilaksanakan oleh POUK Ekklesia Batujajar. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>katekisasi jemaat baru dilaksanakan oleh POUK Ekklesia Batujajar. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen POUK Ekklesia Batujajar dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03'),
(2, 44, 'Ibadah Minggu POUK Ekklesia Batujajar', 'pouk-ekklesia-batujajar-ibadah-minggu', 'ibadah minggu bersama digelar oleh POUK Ekklesia Batujajar. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>ibadah minggu bersama digelar oleh POUK Ekklesia Batujajar. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan POUK Ekklesia Batujajar semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03');

INSERT INTO posts (station_id, category_id, title, slug, excerpt, body, type, is_published, published_at, created_at, updated_at) VALUES
(2, 45, 'Perjamuan Kasih POUK Maranatha Yonkav 1', 'pouk-maranatha-yonkav-1-perjamuan-kasih', 'perjamuan kasih digelar oleh POUK Maranatha Yonkav 1. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.', '<p>perjamuan kasih digelar oleh POUK Maranatha Yonkav 1. Acara berlangsung penuh sukacita dan dihadiri jemaat serta pelayan gereja.</p><p>Kegiatan ini merupakan wujud komitmen POUK Maranatha Yonkav 1 dalam membangun persekutuan dan pelayanan di lingkungan PGIW Jawa Barat.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03'),
(2, 45, 'Persekutuan Doa POUK Maranatha Yonkav 1', 'pouk-maranatha-yonkav-1-persekutuan-doa', 'persekutuan doa rutin dilaksanakan oleh POUK Maranatha Yonkav 1. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.', '<p>persekutuan doa rutin dilaksanakan oleh POUK Maranatha Yonkav 1. Kegiatan berjalan lancar mendapat dukungan penuh dari jemaat dan pengurus.</p><p>Semoga melalui kegiatan ini pelayanan POUK Maranatha Yonkav 1 semakin bertumbuh dan menjadi berkat bagi masyarakat sekitar.</p>', 'article', 1, '2026-06-02 20:39:03', '2026-06-02 20:39:03', '2026-06-02 20:39:03');

