import sys
lines = []
lines.append("")
lines.append("// Invitation -- undangan join studio/komunitas")
lines.append("Route::get('/kredensi/undangan/{token}', function (string $token) {")
lines.append("    $invitation = \\App\\Models\\Invitation::where('token', $token)")
lines.append("        ->where('status', 'pending')")
lines.append("        ->where(function ($q) { $q->whereNull('expires_at')->orWhere('expires_at', '>', now()); })")
lines.append("        ->first();")
lines.append("")
lines.append("    if (!$invitation) {")
lines.append("        return redirect()->route('kredensi')->with('error', 'Undangan tidak valid atau sudah kadaluwarsa.');")
lines.append("    }")
lines.append("")
lines.append("    return view('kredensi-undangan', [")
lines.append("        'invitation' => $invitation,")
lines.append("        'inviter' => $invitation->inviter,")
lines.append("        'community' => $invitation->community,")
lines.append("        'studio' => $invitation->studio,")
lines.append("    ]);")
lines.append("})->name('kredensi.undangan');")
lines.append("")
lines.append("Route::post('/kredensi/undangan/{token}/terima', function (Illuminate\\Http\\Request $request, string $token) {")
lines.append("    $invitation = \\App\\Models\\Invitation::where('token', $token)")
lines.append("        ->where('status', 'pending')")
lines.append("        ->where(function ($q) { $q->whereNull('expires_at')->orWhere('expires_at', '>', now()); })")
lines.append("        ->firstOrFail();")
lines.append("")
lines.append("    if (auth()->check()) { $user = auth()->user(); } else {")
lines.append("        $validated = $request->validate([")
lines.append("            'name' => 'required|string|max:255',")
lines.append("            'email' => 'required|email|unique:users,email',")
lines.append("            'password' => 'required|min:6|confirmed',")
lines.append("            'phone' => 'nullable|string|max:20',")
lines.append("        ]);")
lines.append("        $user = \\App\\Models\\User::create([")
lines.append("            'name' => $validated['name'],")
lines.append("            'email' => $invitation->email,")
lines.append("            'password' => bcrypt($validated['password']),")
lines.append("            'phone' => $validated['phone'] ?? null,")
lines.append("        ]);")
lines.append("        auth()->login($user);")
lines.append("    }")
lines.append("    $user->role = $invitation->role;")
lines.append("    $user->studio_id = $invitation->studio_id;")
lines.append("    $user->save();")
lines.append("    \\App\\Models\\CommunityMember::updateOrCreate(")
lines.append("        ['user_id' => $user->id, 'community_id' => $invitation->community_id],")
lines.append("        ['role' => $invitation->role, 'status' => 'approved', 'joined_at' => now()]")
lines.append("    );")
lines.append("    $invitation->status = 'accepted';")
lines.append("    $invitation->save();")
lines.append("    return redirect()->route('kredensi.tulis')->with('success', 'Selamat datang di ' . $invitation->community->name . '!');")
lines.append("})->name('kredensi.undangan.terima');")

with open("/var/www/radio/routes/web.php", "a") as f:
    f.write("\n".join(lines))
print("Routes appended OK")
